# Generated by Django 3.2.15 on 2022-08-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodationName', models.CharField(max_length=100)),
                ('AccomodationAddress', models.CharField(max_length=100)),
                ('AccomodationImg', models.CharField(max_length=100)),
                ('AccomodationCategory', models.CharField(max_length=100)),
                ('AccomodationLink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(max_length=100)),
                ('placePic', models.CharField(max_length=100)),
                ('placeAddress', models.CharField(max_length=100)),
                ('placePhone', models.CharField(max_length=100)),
                ('placeLink', models.CharField(max_length=100)),
                ('placeCategory', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dang.location')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='사용자 아이디')),
                ('password', models.CharField(max_length=64, verbose_name='사용자 비밀번호')),
                ('email', models.EmailField(max_length=128, null=True, verbose_name='사용자 이메일')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postType', models.CharField(max_length=100)),
                ('postGood', models.CharField(max_length=100)),
                ('postBad', models.CharField(max_length=100)),
                ('postImage', models.CharField(max_length=100)),
                ('ranking', models.CharField(max_length=100)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dang.accomodation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dang.location')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dang.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dang.user')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalName', models.CharField(max_length=100)),
                ('medicalPhone', models.CharField(max_length=100)),
                ('medicalAddress', models.CharField(max_length=100)),
                ('medicalLocation', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dang.location')),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafeName', models.CharField(max_length=100)),
                ('cafePhone', models.CharField(max_length=100)),
                ('cafeAddress', models.CharField(max_length=100)),
                ('cafeLink', models.CharField(max_length=100)),
                ('cafeImg', models.CharField(max_length=100)),
                ('cafeCategory', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dang.location')),
            ],
        ),
        migrations.AddField(
            model_name='accomodation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dang.location'),
        ),
    ]
