# Generated by Django 4.1 on 2022-08-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomodation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medical',
            options={},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
