# Generated by Django 4.0.6 on 2022-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='medicalAddress',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='medical',
            old_name='medicalLocation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='medical',
            old_name='medicalName',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='medicalPhone',
        ),
        migrations.AddField(
            model_name='medical',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='doro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='hourInfo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='y',
            field=models.FloatField(null=True),
        ),
    ]
