# Generated by Django 4.0.6 on 2022-08-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='like',
            field=models.BooleanField(default=False, verbose_name='즐겨찾기'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='like',
            field=models.BooleanField(default=False, verbose_name='즐겨찾기'),
        ),
        migrations.AddField(
            model_name='place',
            name='like',
            field=models.BooleanField(default=False, verbose_name='즐겨찾기'),
        ),
    ]
