# Generated by Django 3.2.15 on 2022-08-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0002_alter_accomodation_options_alter_medical_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dogname',
            field=models.CharField(max_length=15, null=True, verbose_name='강아지 이름'),
        ),
    ]
