# Generated by Django 4.0.6 on 2022-08-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0002_accomodation_like_cafe_like_place_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False, verbose_name='즐겨찾기')),
            ],
        ),
        migrations.RemoveField(
            model_name='accomodation',
            name='like',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='like',
        ),
        migrations.RemoveField(
            model_name='place',
            name='like',
        ),
    ]
