# Generated by Django 3.2.15 on 2022-08-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0003_user_dogname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dogname',
        ),
    ]
