# Generated by Django 4.1 on 2022-08-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0003_cafe_star'),
        ('dang', '0004_remove_user_dogname'),
    ]

    operations = [
    ]
