# Generated by Django 4.0.6 on 2022-08-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0004_remove_favorite_favorite_favorite_already_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='already_like',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='like',
            field=models.BooleanField(default=False, verbose_name='찜하기'),
        ),
    ]
