# Generated by Django 4.0.6 on 2022-08-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0005_remove_favorite_already_like_alter_favorite_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='좋아요')),
            ],
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
