# Generated by Django 4.0.6 on 2022-08-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0005_merge_0003_cafe_star_0004_remove_user_dogname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, upload_to='', verbose_name='post_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ranking',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
