# Generated by Django 4.0.6 on 2022-08-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0006_comment_delete_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='찜')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
