# Generated by Django 4.0.6 on 2022-08-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0007_remove_post_accomo_remove_post_cafe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postBad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postGood',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
    ]
