# Generated by Django 4.0.6 on 2022-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dang', '0008_alter_post_postbad_alter_post_postgood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postBad',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postGood',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, default='NULL', upload_to='posts/%Y%m%d', verbose_name='사진'),
        ),
    ]
